#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for backend/gpu 
#
# IDENTIFICATION
#    src/backend/gpu/Makefile
#
#-------------------------------------------------------------------------

# subdir = src/gausskernel/gpu
# top_builddir = ../../../
# include $(top_builddir)/src/Makefile.global

# OBJS = gpuInit.o gpuExec.o tableScan.o hashJoin.o groupby.o

# include $(top_srcdir)/src/gausskernel/common.mk
